[project]
name = "app-8-instant-dictionary-webapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "justpy>=0.14.0",
    "pandas>=2.2.3",
]
